apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgres","namespace":"default"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"postgres"}}}
  creationTimestamp: "2025-12-09T00:47:13Z"
  name: postgres
  namespace: default
  resourceVersion: "173339"
  uid: aad3ddf7-fbb8-4f3b-8b7f-bad330be1a8c
spec:
  clusterIP: 10.107.154.39
  clusterIPs:
  - 10.107.154.39
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
