version: 2

models:
  - name: weekly_metrics_summary
    description: "Weekly auction performance metrics by fiscal week"
    columns:
      - name: fiscal_year
        description: "Fiscal year (Aug 1 - Jul 31), e.g. 2026"
      - name: fiscal_week_number
        description: "Week number within fiscal year (1-52)"
      - name: total_items_sold
        description: "Count of items sold (safe_for_alv = true)"
      - name: avg_lot_value
        description: "Average contract price for sold items"
      - name: total_contract_price
        description: "Sum of all contract prices"